### ISSUE TITLE
Doesn't start with cron

### ISSUE THREAD

**Issue by Fabian42** [Suppen/TediCross#51] opened 2018-01-11 20:37 UTC
This might be a problem on my end and not a bug, but I don't know where that problem would be. So I report this and hope that either it actually is a bug and it can be fixed or that I can abuse this as a support forum. :D

Command in terminal: `cd /home/pi/Downloads/TediCross-master/ && sudo npm start` works.
Command in cron: `cd /home/pi/Downloads/TediCross-master/ && sudo npm start` doesn't work.

Confirmed by starting it a second time in terminal and waiting for error messages: None, so bot wasn't running.

**Comment by Suppen** [comment] 2018-01-11 20:57
Have you tried using the absolute path to `npm`? You find it by running `whereis npm`. Mine is `/usr/bin/npm`, so the cron command would be
```
cd /home/pi/Downloads/TediCross-master/ && /usr/bin/npm start`
```

Also, why are you running it as root (`sudo`)? And what are you trying to achieve by using `cron`?

**Comment by Fabian42** [comment] 2018-01-11 21:50
`sudo` was just a try, because I read that cron often has problems with permissions.
Cron is set up to start TediCross at boot.
Actually, I just restarted my Raspberry Pi to test it and the bot is running. However, when I stop the process and then try to start it again using the cron GUI, it does not start. Is that a Cron bug? If yes, where can I report it?

**Comment by Suppen** [comment] 2018-01-12 08:17
I know `cron` can be used to start things on boot, but I have never gotten that to work myself. Also, I didn't even know `cron` had a GUI

The recommended way of making something start at boot is by using `systemd`. Getting started with it is a bit scary and confusing, but once you get going, it's actually quite simple.

All of the following requires root privileges, unless otherwise noted

Basically, make a file named `tedicross.service` in `/etc/systemd/system/` and fill it with this:
```
[Service]
ExecStart=/usr/bin/node main.js
WorkingDirectory=/home/tedicross/TediCross
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=tedicross
User=tedicross
Group=tedicross
Environment=TELEGRAM_BOT_TOKEN=secret1
Environment=DISCORD_BOT_TOKEN=secret2

[Install]
WantedBy=multi-user.target
```

Modify it to your needs. Here I have it running as a dedicated user, `tedicross`, but you can use the `pi` user if you want. I'm also giving the bot's tokens as environment parameters instead of through the settings file. See the README for details.

Output from the bot foes to `/var/log/messages/` with the identifier `tedicross`

After putting the file there, run `systemctl enable tedicross` and then `systemctl start tedicross`. It should now be set up to run when the computer boots. To verify it is indeed running, run `systemctl status tedicross` (no root needed). You also have `systemctl restart tedicross` and `systemctl stop tedicross`

**Comment by Fabian42** [comment] 2018-01-15 18:07
I just had it running in background (started by cron) and at 7:29 I got a message (started the bot yesterday), but at 12:19 it didn't work anymore.
I tried to start a second instance in a root terminal (just because that's my new default) and I get spammed with this multiple times per second:
>Couldn't fetch Telegram messages. Reason: Error: getaddrinfo EAI_AGAIN api.telegram.org/443
at Object._errnoException (util.js:1022:11)
at errnoException (dns.js:55:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Request error: { Error: getaddrinfo EAI_AGAIN api.telegram.org/443
at Object._errnoException (util.js:1022:11)
at errnoException (dns.js:55:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
code: 'EAI_AGAIN'
errno: 'EAI_AGAIN'
syscall: 'getaddrinfo'
hostname: 'api.telegram.org'
host: 'api.telegram.org'
port: 443 }

That is a different error than what I usually get when starting the bot in a second instance, so I'm not really sure what's happening. I also can't get the error message of the first instance, because it doesn't show a terminal.

**Comment by Suppen** [comment] 2018-01-16 07:57
I'm not a cron poweruser, but according to [this](https://askubuntu.com/questions/56683/where-is-the-cron-crontab-log), cronjobs put their output in `/var/log/syslog`. Check there.

What I usually do with cronjobs is to make a script which `cd`s into the working directory and runs whatever command it should run with the output streams redirected to file. But again, for running a service whenever the server starts, systemd is the way to go.

The second error looks like a DNS error. Your server cannot find the address api.telegram.org for some reason. It's a network issue, not a TediCross issue. Hopefully it's just temporary.

**Comment by Fabian42** [comment] 2018-01-16 18:10
I figured out why I was so confused all the time: Clicking the "run" button in cron apparently does absolutely nothing. That in combination with not seeing anything made it really difficult.
I failed to open a terminal with TediCross in it (even though the exact same command works from another terminal), so I at least redirected the output to a file. It seems like it does start consistently at boot if the command is `cd /home/pi/Downloads/TediCross-master/ && npm start`.
Now that I can at least somewhat see what's happening, I'll wait for things to happen. It seems to me like the bot stops working when the device gets disconnected from the internet and then doesn't continue when the connection is back. But I'm not sure, that's one of the things I will test.

**Comment by Suppen** [comment] 2018-01-17 09:14
I'm closing this issue as it is not a problem with TediCross, but a general cron problem

**Closed by Suppen** 2018-01-17 09:14 UTC

**Comment by Suppen** [comment] 2018-01-17 09:15
`It seems to me like the bot stops working when the device gets disconnected from the internet and then doesn't continue when the connection is back`

This is what I believe is the cause of https://github.com/Suppen/TediCross/issues/15, but I have been unable to recreate it

**Comment by Fabian42** [comment] 2018-01-17 21:17
At 13:26 and 13:50 I got a huge pile of error messages, but there were no internet problems at that time. I'll try to connect it to LAN now and see if it still happens. It hasn't lasted 24 hours yet without crashing.

**Comment by Fabian42** [comment] 2018-01-27 21:37
Yep, it definitely seems to be #15, combined with weirdness in the Cron UI I'm using. Still happens on LAN and it's definitely not related to connection loss (cable is fine and router log shows no problems at the error time).
