### ISSUE TITLE
JSON error on start

### ISSUE THREAD

**Issue by Fabian42** [Suppen/TediCross#53] opened 2018-01-23 21:36 UTC
I changed nothing about the bot (installed and uninstalled some unrelated packages), also re-downloading doesn't help. Output:
```
root@raspberrypi:/home/pi# cd /home/pi/Downloads/TediCross-master && npm start

> tedicross@0.1.0 start /home/pi/Downloads/TediCross-master
> node main.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Downloads/TediCross-master/lib/Logger.js:7:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.1.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tedicross@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-23T21_29_32_813Z-debug.log
root@raspberrypi:/home/pi/Downloads/TediCross-master# 
```

settings.json:
```
{
	"telegram": {
		"auth": {
			"token": "<censored>"
		},
		"useFirstNameInsteadOfUsername": false,
		"commaAfterSenderName": false,
		"colonAfterSenderName": false,
		"skipOldMessages": false,
		"sendEmojiWithStickers": true
	},
	"discord": {
		"auth": {
			"token": "<censored>"
		},
		"skipOldMessages": false
	},
	"debug": false,
	"bridgeMap": [
		{
			"name": "announcements",
			"telegram": -294472349,
			"discord": {
				"guild": "173877869640941568",
				"channel": "235052833630584832"
			}
		},
		{
			"name": "general",
			"telegram": -264625058,
			"discord": {
				"guild": "173877869640941568",
				"channel": "173877869640941568"
			}
		},
		{
			"name": "fanserver",
			"telegram": -258044072,
			"discord": {
				"guild": "173877869640941568",
				"channel": "243076315664744449"
			}
		},
		{
			"name": "patron",
			"telegram": -237765229,
			"discord": {
				"guild": "173877869640941568",
				"channel": "302158891989336065"
			}
		},
		{
			"name": "nomic",
			"telegram": -316253909,
			"discord": {
				"guild": "173877869640941568",
				"channel": "297670830802993153"
			}
		},
		{
			"name": "memes",
			"telegram": -277476841,
			"discord": {
				"guild": "173877869640941568",
				"channel": "350544518333988864"
			}
		},
		{
			"name": "version-discussion",
			"telegram": -258054368,
			"discord": {
				"guild": "173877869640941568",
				"channel": "381490427255324672"
			}
		},
		{
			"name": "moderators",
			"telegram": -286778738,
			"discord": {
				"guild": "173877869640941568",
				"channel": "235053449882894336"
			}
		},
		{
			"name": "moderationlog",
			"telegram": -283606636,
			"discord": {
				"guild": "173877869640941568",
				"channel": "284807244485361675"
			}
		}
	]
}
```

The mentioned log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tedicross@0.1.0~prestart: tedicross@0.1.0
6 info lifecycle tedicross@0.1.0~start: tedicross@0.1.0
7 verbose lifecycle tedicross@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle tedicross@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Downloads/TediCross-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle tedicross@0.1.0~start: CWD: /home/pi/Downloads/TediCross-master
10 silly lifecycle tedicross@0.1.0~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle tedicross@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle tedicross@0.1.0~start: Failed to exec start script
13 verbose stack Error: tedicross@0.1.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid tedicross@0.1.0
15 verbose cwd /home/pi/Downloads/TediCross-master
16 verbose Linux 4.9.59-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error tedicross@0.1.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the tedicross@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I can't find `module.js`, so I can't tell you what that line says.

**Comment by Suppen** [comment] 2018-01-24 06:32
Try running `npm install`

**Comment by Fabian42** [comment] 2018-01-24 06:58
Oh, yes, I forgot that after redownloading. But I'm pretty sure that I got the same error in the old, previously working installation. I'll try this afternoon.

**Comment by Fabian42** [comment] 2018-01-24 17:32
Yes, there I get the same error and trying to install doesn't work (because it's already installed). Well, I guess I'll see if I get the same error on the new installation one day.

**Comment by Suppen** [comment] 2018-01-25 16:42
Is moment listed in the file package.json?

**Comment by Fabian42** [comment] 2018-01-25 16:51
No. The file content is:
{
  "name": "tedicross",
  "version": "0.1.0",
  "description": "Better DiteCross",
  "scripts": {
    "start": "node main.js"
  },
  "dependencies": {
    "discord.js": "^11.2.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "simple-markdown": "^0.2.1",
    "teleapiwrapper": "^2.3.0"
  }
}

**Comment by Suppen** [comment] 2018-01-26 06:14
Well, moment is there. Fifth line from the bottom. It should be installed when you run `npm install`

**Comment by Fabian42** [comment] 2018-01-26 07:08
Oh, I overlooked it. Anyway, that file is the same in the working and the
not working version. I can compare the version numbers in about 10 hours.

**Comment by Suppen** [comment] 2018-01-26 12:42
I don't know what the problem is, then. Try a reinstall of TediCross

**Comment by Fabian42** [comment] 2018-01-26 12:45
As I said, the new installation works. I just want to know how it happened
and if it could happen again. Should I send you an archive of the working
and of the not working version?

**Comment by Suppen** [comment] 2018-01-26 14:14
I don't know how it happened. You mentioned installing/uninstalling unrelated packages. Maybe [this](https://www.bennadel.com/blog/2169-where-does-node-js-and-require-look-for-modules.htm) can help

I'm closing this issue as it is not a TediCross problem

**Closed by Suppen** 2018-01-26 14:14 UTC
